### ISSUE TITLE
Save grid geometric data (lat, lon) in the output nc file

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#1627]
I was surprised to see property check failure printing

```
    minimum:
      - value: -1
      - entry: (134,1)
      - lat/lon: (-40.1244, 237.438)
    maximum:
      - value: -1
      - entry: (134,1)
      - lat/lon: (-40.1244, 237.438)
```
since I thought lon was always in [-180,180). I actually thought lat/lon were in radians. So I went to check the values in the output file, but did not find them, and realized we never save lat/lon. We should probably take care of that.
