### ISSUE TITLE
Incorrect restart writing behavior

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#2110]
I'm not sure if this an issue or not, but wanted to document to remind myself of details.

I launched a case to run for 1 month, with a restart at the end. I then continued it for another month. All fine.
Then I wanted to continue for 10 more days with a restart every 5th day. Not that it matters, but the reason
for this was to get a restart closer to a crash. 
```
Results in group run_begin_stop_restart
        STOP_N: 10
        STOP_OPTION: ndays
        REST_N: 5
        REST_OPTION: ndays
        CONTINUE_RUN: TRUE
```
The run completed, but I don't see the `scream.r` restarts being written. Normally, I would see a restart file written for elm,cice,scream,cpl, which is true for the 2 jobs that run for a month. But for the job running for 10 days, with 5-day restarts, I don't see any new scream.r files ?

```
login17% lr run/*.r.*
  402200488 Dec 28 11:17 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.elm.r.0001-02-01-00000.nc
    6060120 Dec 28 11:17 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.cice.r.0001-02-01-00000.nc
 1072756880 Dec 28 11:17 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.scream.r.0001-02-01-00000.nc
   41796488 Dec 28 11:17 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.cpl.r.0001-02-01-00000.nc
    6060120 Dec 28 11:58 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.cice.r.0001-03-01-00000.nc
  402200488 Dec 28 11:58 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.elm.r.0001-03-01-00000.nc
 1072756880 Dec 28 11:58 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.scream.r.0001-03-01-00000.nc
   41796488 Dec 28 11:58 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.cpl.r.0001-03-01-00000.nc
    6060120 Dec 28 12:03 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.cice.r.0001-03-06-00000.nc
  402200488 Dec 28 12:03 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.elm.r.0001-03-06-00000.nc
   41796488 Dec 28 12:03 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.cpl.r.0001-03-06-00000.nc
    6060120 Dec 28 12:04 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.cice.r.0001-03-11-00000.nc
  402200488 Dec 28 12:04 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.elm.r.0001-03-11-00000.nc
   41796488 Dec 28 12:04 run/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.cpl.r.0001-03-11-00000.nc

/pscratch/sd/n/ndk/e3sm_scratch/pm-gpu/se48-dec26/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2
```

And, looking at rpointer files, I see:
```
atmdate=0001-03-01-00000
drvdate=0001-03-11-00000
lnddate=0001-03-11-00000
icedate=0001-03-11-00000
ocndate=0001-03-11-00000
```
ie, the date in rpointer.atm appears to be the wrong date? (and, of course, there are no restart files for ATM)

**Comment by bartgol** [comment]
Just reading this after returning from vacation. 

> ```
> Results in group run_begin_stop_restart
>         STOP_N: 10
>         STOP_OPTION: ndays
>         REST_N: 5
>         REST_OPTION: ndays
>         CONTINUE_RUN: TRUE
> ```
For the 5-days restart job, can you check what was the content of this sublist in the `scream_input.yaml` file in `run/data`? It should contain
```
Scorpio:
  model_restart:
    Casename: <your_case_name>
    output_control:
      Frequency:       5
      frequency_units: nsteps
```
but maybe something is amiss in our restart logic. If that's indeed the yaml file content, then we need to check what else could prevent the writing of the restart file.

**Comment by ambrad** [comment]
@bartgol are you going to take this issue? If so, assign yourself and remove the "help wanted" tag. I'm pushing us to try to keep the "help wanted" issues a tidy list of immediately actionable dev items up for grabs so devs always have something to do when they have free cycles.

**Comment by ndkeen** [comment]
Luca: indeed it looks like `run/data/scream)input.yaml` not updating the frequency units?

```
login20% head -16 run/data/scream_input.yaml
################################################################
# Do NOT modify this file. It is generated by scream/buildnml using
# the data from $case/namelist_scream.xml. If you want to make some
# local changes, you can edit this XML file or use atmchange.
################################################################
Scorpio:
  model_restart:
    Casename: ./f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2.scream
    output_control:
      Frequency: 1
      avg_type_in_filename: false
      frequency_in_filename: false
      frequency_units: nmonths
  output_yaml_files:
  - /pscratch/sd/n/ndk/e3sm_scratch/pm-gpu/se48-dec26/f30.F2010-SCREAMv1.ne30pg2_ne30pg2.se48-dec26.gnugpu.1m.n004a4xX14444.so108n8.wr.s2/run/data/spiffy.yaml
atmosphere_processes:
```
