### ISSUE TITLE
./case.setup still not copying non-default atm_procs to namelist_scream.xml

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#2410]
The issue is when we have an atmosphere process that we have defined but do not want to be in the default atmosphere list.  In this case, the nudging process is not a default process in the `atm_procs_list` but we do want to have the ability to add it to the procs list for certain cases.

`./case.setup` does not appear to copy the XML options for a process unless it is listed as a process in the process list by default.

Note, there is a test process defined in `namelist_defaults_scream.xml` called `testOnly` which should presumably be available in the `namelist_scream.xml` file in the case_scripts directory, but it isn't present.

I think this was supposed to be fixed by #2375, but there may be something in my use case that is still causing the older behavior.

For reproducibility I am using the built in `./cime/scripts/create_test` tool to set the run up.  The case is `SMS_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1`.

**Comment by AaronDonahue** [comment]
@jgfouca , I'm pinging you to see if you can check that I'm not doing something incorrect in my setup.

@elynnwu , pinging you to track the issue since I believe you are also experiencing the same issue.

**Comment by bartgol** [comment]
IIRC, the intermediate XML file in the case dir  is re-generated every time buildnml runs. As such, you don't need to copy stuff that is not used in that XML file. If you want to change an atm proc, I _think_ you should be able to atmchange the proc list, and the next buildnml will grab it from the defaults in the src tree, and add it to the xml in the case dir...

**Comment by AaronDonahue** [comment]
Yes, that whats we expected, but in practice using `atmchange` to add a process to the process list doesn't result in the full section for that process being added to the namelist file.  At least that is what @elynnwu and I have both experienced independently.  So we see, say `nudging`, will be listed in the `atm_proc_list`, but we don't see the `nudging` entry with all of the parameter options for nudging in the `scream_input.yaml` file.

Is it possible that we need to rebase off of the latest master (or merge it) to get recent changes to the buildnml?  @elynnwu , could you see if merging master and then using `./atmchange atm_proc_list=x,y,z,nudging` works?

**Comment by bartgol** [comment]
Ok, I think I will have to debug this use case by hand, to see where exactly the culprit is. Can you please paste here the sequence of commands you run?

**Comment by AaronDonahue** [comment]
I'm on vacation, but still secretly checking Slack and git :-)  So forgive me if the commands are not perfect... @elynnwu can correct if what I write doesn't work.

Grab the `nudging` branch, `aarondonahue/nudging`,

Set up the case with something like
```
./cime/scripts/create_test SMS_Ld1_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1.${machine}_${compiler}
```
Then when that's all said and done go to the case_scripts directory and use atmchange to add `nudging` to the atm_proc_list
```
./atmchange physics::atm_procs_list="(mac_aero_mic,rrtmgp,nudging)"
```

Then run `./case.setup` to build the nml and check `run/data/scream_input.yaml`.  You should see `nudging` listed as a atm_proc like you expect, but won't see parameter list for the nudging process itself.  The one associated w/
```
    <nudging inherit="atm_proc_base">
      <nudging_filename type="array(string)">NONE</nudging_filename>
      <nudging_fields type="array(string)">NONE</nudging_fields>
      <nudging_timescale type="integer">0</nudging_timescale>
      <source_pressure_type type="string">DYNAMIC</source_pressure_type>
    </nudging>
```

**Comment by bartgol** [comment]
Ok, I'll take a look today. Thanks.

**Comment by jgfouca** [comment]
@AaronDonahue , sorry for the slow response. I did not look at github much during the E3SM all hands. I will take a look at this since it's similar to what I was working on before.

**Comment by jgfouca** [comment]
@AaronDonahue , I tested this with the `testOnly` atm_proc and things appear to work as intended. 

```
% ./create_test SMS_Ld1_P96x1.ne4pg2_ne4pg2.F2010-SCREAMv1 --no-build
% cd $case
% grep -R testOnly *
* nothing found *
% ./atmchange mac_aero_mic::atm_procs_list='(shoc,cldFraction,spa,p3,testOnly)'
% ./case.setup
% grep -R testOnly *
* There are now full atm_proc blocks for testOnly in both namelist_scream.xml and run/data/scream_input.yaml *
```

Were you expecting to see the testOnly blocks populated, even though it was not in atm_proc_list, before the atmchange?

**Comment by jgfouca** [comment]
@bartgol , @AaronDonahue , I think the question is what atm_procs should our buildnml populate. The current implementation looks at `atm_procs_list` and only populates those. As an alternative, we could populate everything that inherits `atm_proc_base`.

**Comment by bartgol** [comment]
No, it's ok to populate only with the procs that are used. There is really no need to populate everything that inherit from `atm_proc_base`. If the user atmchanges the proc list, we still open the defaults file in the src tree, to get the specs of the proc, so there would really be no advantage in populating the XML with all procs.

@jgfouca can you try to add some fake params to `testOnly` (in the defaults XML file in our src tree), and verify that the commands you used above also populate the case dir XML with those fake params?

**Comment by bartgol** [comment]
@AaronDonahue I just tried your commands on your nudging branch, and it works as expected. After case creation/setup, I ran `atmquery --listall`, and saw no nudging. I ran `./atmchange physics::atm_procs_list="(mac_aero_mic,rrtmgp,nudging)"`, and then atmquery was finding nudging:

```
  physics
      atm_procs_list: (mac_aero_mic,rrtmgp,nudging)
      Type: Group
      schedule_type: Sequential
      number_of_subcycles: 1
      enable_precondition_checks: true
      enable_postcondition_checks: true
      repair_log_level: trace
      internal_diagnostics_level: 0
      compute_tendencies: NONE
      mac_aero_mic
          atm_procs_list: (shoc,cldFraction,spa,p3)
          number_of_subcycles: 24
          Type: Group
          schedule_type: Sequential
          enable_precondition_checks: true
          enable_postcondition_checks: true
          repair_log_level: trace
          internal_diagnostics_level: 0
          compute_tendencies: NONE
          shoc
              enable_column_conservation_checks: false
              number_of_subcycles: 1
              enable_precondition_checks: true
              enable_postcondition_checks: true
              repair_log_level: trace
              internal_diagnostics_level: 0
              compute_tendencies: NONE
          cldFraction
              number_of_subcycles: 1
              enable_precondition_checks: true
              enable_postcondition_checks: true
              repair_log_level: trace
              internal_diagnostics_level: 0
              compute_tendencies: NONE
          spa
              spa_remap_file: /home/lbertag/workdir/e3sm/e3sm-data/inputdata/atm/scream/maps/map_ne30np4_to_ne4pg2_mono.20220714.nc
              spa_data_file: /home/lbertag/workdir/e3sm/e3sm-data/inputdata/atm/scream/init/spa_file_unified_and_complete_ne30_20220428.nc
              number_of_subcycles: 1
              enable_precondition_checks: true
              enable_postcondition_checks: true
              repair_log_level: trace
              internal_diagnostics_level: 0
              compute_tendencies: NONE
          p3
              do_prescribed_ccn: true
              do_predict_nc: true
              enable_column_conservation_checks: false
              tables: 
        /home/lbertag/workdir/e3sm/e3sm-data/inputdata/atm/scream/tables/p3_lookup_table_1.dat-v4.1.1,
        /home/lbertag/workdir/e3sm/e3sm-data/inputdata/atm/scream/tables/mu_r_table_vals.dat8,
        /home/lbertag/workdir/e3sm/e3sm-data/inputdata/atm/scream/tables/revap_table_vals.dat8,
        /home/lbertag/workdir/e3sm/e3sm-data/inputdata/atm/scream/tables/vn_table_vals.dat8,
        /home/lbertag/workdir/e3sm/e3sm-data/inputdata/atm/scream/tables/vm_table_vals.dat8
      
              number_of_subcycles: 1
              enable_precondition_checks: true
              enable_postcondition_checks: true
              repair_log_level: trace
              internal_diagnostics_level: 0
              compute_tendencies: NONE
      rrtmgp
          rrtmgp_coefficients_file_sw: /home/lbertag/workdir/e3sm/e3sm-data/inputdata/atm/scream/init/rrtmgp-data-sw-g112-210809.nc
          rrtmgp_coefficients_file_lw: /home/lbertag/workdir/e3sm/e3sm-data/inputdata/atm/scream/init/rrtmgp-data-lw-g128-210809.nc
          rrtmgp_cloud_optics_file_sw: /home/lbertag/workdir/e3sm/e3sm-data/inputdata/atm/scream/init/rrtmgp-cloud-optics-coeffs-sw.nc
          rrtmgp_cloud_optics_file_lw: /home/lbertag/workdir/e3sm/e3sm-data/inputdata/atm/scream/init/rrtmgp-cloud-optics-coeffs-lw.nc
          column_chunk_size: 1280
          active_gases: h2o, co2, o3, n2o, co, ch4, o2, n2
          ch4vmr:  1807.851e-9  
          co2vmr:  388.717e-6   
          n2ovmr:  323.141e-9   
          f11vmr:  768.7644e-12 
          f12vmr:  531.2820e-12 
          n2vmr:  0.7906       
          covmr:  1.0e-7       
          orbital_year: 2010
          orbital_eccentricity: -9999
          orbital_obliquity: -9999
          orbital_mvelp: -9999
          rad_frequency: 1
          do_aerosol_rad: true
          enable_column_conservation_checks: false
          number_of_subcycles: 1
          enable_precondition_checks: true
          enable_postcondition_checks: true
          repair_log_level: trace
          internal_diagnostics_level: 0
          compute_tendencies: NONE
      nudging
          nudging_filename: NONE
          nudging_fields: NONE
          nudging_timescale: 0
          source_pressure_type: DYNAMIC
          number_of_subcycles: 1
          enable_precondition_checks: true
          enable_postcondition_checks: true
          repair_log_level: trace
          internal_diagnostics_level: 0
          compute_tendencies: NONE
```
and it was also in `run/data/scream_input.yaml`. Perhaps we're not really understanding your issue?
